import { Inter } from "next/font/google";
import "./globals.css";
import "./globals-phone.css";
import Image from "next/image";

// The following import prevents a Font Awesome icon server-side rendering bug,
// where the icons flash from a very large icon down to a properly sized one:
import '@fortawesome/fontawesome-svg-core/styles.css';
// Prevent fontawesome from adding its CSS since we did it manually above:
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false; /* eslint-disable import/first */


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">

      <body className={inter.className}>


        {/* Background image wood */}
        <Image 
          // src="/plant-bg-min.png"
          src="/wood-bg.jpeg"
          fill={true}
          style={{opacity: "0.7", zIndex:"0"}}
        />
        
        {children}
        
        
        
        </body>



    </html>
  );
}
